<h1><div class="text-center">THE TEMPLATE</div><small><div class="text-center">fast. basic. design.<br></div></small></h1>
<p></p><div style="text-align: center;"><img src="http://placehold.it/800x180" class="img-thumbnail protected" <="" div=""><div style="text-align: center;"><br></div><div style="text-align: center;">
    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
    At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
    At vero eos et accusam et justo duo dolores et ea rebum.
    <br><br>
  <img src="http://placehold.it/300x300" class="img-circle"><br><br>Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
    At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Duis autem vel
    eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto
    odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing
    elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.

Ut wisi?</div><div style="text-align: center;"><br></div>
  <div style="text-align: center;"><img src="http://placehold.it/1200x220" class="img-thumbnail"></div><div style="text-align: center;">
    <h1><div style="text-align: center;">THE SOFTWARE</div><small><div style="text-align: center;">best open source.</div><div style="text-align: center;"><br><br><br><br><br><br></div><div style="text-align: center;"><br><br></div><div style="text-align: center;"><div style="text-align: center;"><span style="color: rgb(0, 0, 0); font-family: " source="" sans="" pro",="" "helvetica="" neue",="" helvetica,="" arial,="" sans-serif;="" font-size:="" 17.5px;="" line-height:="" 25px;="" text-align:="" left;"="">PHP5, jQuery, Bootstrap, Google Fonts, AdminLTE</span></div><small style="text-align: center; font-size: 14px; display: block; line-height: 1.42857; font-family: " source="" sans="" pro",="" "helvetica="" neue",="" helvetica,="" arial,="" sans-serif;"="">dataTables, FontAwesome, Summernote, and many, many more!</small></div></small></h1></div><div style="text-align: right;"><div style="text-align: center;"><br><br><br><br><br><br><br><br></div><div style="text-align: center;"><h1 style="color: rgb(0, 0, 0);"><div>THE FRONTEND</div><small style="font-size: 23.4px;">modern. slick. versatile.?<br><br><br><br><br><br><br></small></h1></div><div style="text-align: center;"><br></div><div style="text-align: center;"><div style="color: rgb(119, 119, 119); font-family: " source="" sans="" pro",="" sans-serif;="" font-size:="" 23.4px;="" line-height:="" 23.4px;"=""><span source="" sans="" pro",="" "helvetica="" neue",="" helvetica,="" arial,="" sans-serif;="" font-size:="" 17.5px;="" line-height:="" 25px;="" text-align:="" left;"="" style="color: rgb(0, 0, 0);">YaWK's powerful rendering Engine</span></div><small source="" sans="" pro",="" "helvetica="" neue",="" helvetica,="" arial,="" sans-serif;"="" style="font-size: 14px; line-height: 1.42857; color: rgb(119, 119, 119); font-family: " sans-serif;="" display:="" block;"="">create beautiful dynamic pages, from small business to enterprise.</small></div><div style="text-align: center;"><br></div><div style="text-align: center;"><br></div><div style="text-align: center;"><br></div><div style="text-align: center;"><br></div><div style="text-align: center;"><br></div><div style="text-align: center;"><br></div><div style="text-align: center;"><br></div><div style="text-align: center;"><br></div><div style="text-align: center;"><br></div><div style="text-align: center;"><br></div><div style="text-align: center;"><br></div><div style="text-align: center;"><br></div><div style="text-align: center;"><br></div><div style="text-align: center;"><br></div><div style="text-align: center;"><br></div><div style="text-align: center;"><br></div><div style="text-align: center;"><span style="line-height: 1.42857;">F I N</span></div></div><p></p>       </div>              